@host=http://localhost:7071


### Ask what the weather is in a place to trigger GetWeather function
POST  {{host}}/api/prompt
Content-Type: application/json

{
    "Prompt": "What is the weather in Tacoma, WA?"
}
